paths:
  rawData: '/Users/ksharma/Documents/ML Engineer/Machine Learning/Projects/FinancialNewsSentimentAnalysis/Data/01_RawData/all-data.csv'  
  reports: '/Users/ksharma/Documents/ML Engineer/Machine Learning/Projects/FinancialNewsSentimentAnalysis/Reports/Figures'