paths:
  rawData: '/Users/ksharma/Documents/ML Engineer/Machine Learning/Projects/FinancialNewsSentimentAnalysis/Data/01_RawData/all-data.csv'  
  reports: '/Users/ksharma/Documents/ML Engineer/Machine Learning/Projects/FinancialNewsSentimentAnalysis/Reports/Figures'
  trainedModels: '/Users/ksharma/Documents/ML Engineer/Machine Learning/Projects/FinancialNewsSentimentAnalysis/Modeling/Trained Models'
hyperparameters:
  logisticRegression:
    param_grid: 
      'penalty': ['l1','l2', 'elasticnet', 'none']
      'multi_class': ['multinomial']
      'C': [.1, .01, 1]
  randomForestClassifier:
    param_grid:
      'n_estimators': [100, 200, 300]
      'max_depth': [3, 5, 7]
      'max_features': ['auto', 'sqrt', 'log2']
      'min_samples_split': [2, 4, 6]
      'random_state': [24]
      'n_jobs': -1
  linearSVC:
    param_grid:
      'penalty': ['l1','l2']
      'C': [.1, .01, 1]
      'multi_class': [‘ovr’, ‘crammer_singer’]
      'max_iter': [750, 100, 1250]
      'random_state': 24